version: '3.5'

services:
  golden-rat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golden-rat
    user: "node"
    working_dir: /golden-rat
    command: >
      bash -c "echo '==== starting ====='
      && mkdir -p /home/node/.npm-global
      && npm config set prefix /home/node/.npm-global
      && export PATH=$PATH:/home/node/.npm-global/bin
      && npm install -g @ionic/cli @angular/cli @capacitor/android
      && chown -R node:node /golden-rat
      && echo '==== done ====='
      && sleep infinity"
    volumes:
      - ..:/golden-rat
    restart: always
    environment:
      - HOME=/home/node
      - PATH=/home/node/.npm-global/bin:$PATH:/home/node/android-sdk/cmdline-tools/latest/bin
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - ANDROID_HOME=/home/node/android-sdk
      - ANDROID_SDK_ROOT=/home/node/android-sdk
    networks:
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.golden-rat.rule=Host(`goldenrat.ingeniouskey.com`)
      - traefik.http.routers.golden-rat.entrypoints=websecure
      - traefik.http.services.golden-rat.loadbalancer.server.port=8100
      - traefik.http.routers.golden-rat.tls=true
      - traefik.http.routers.golden-rat.tls.certresolver=myresolver
    extra_hosts:
      glitchtip.goldenrat.be: 172.17.0.1
      api.goldenrat.be: 172.17.0.1

networks:
  traefik_network:
    external: true
